export const GET_STREAMS = "GET_STREAMS";
export const ADD_STREAM = "ADD_STREAM";
export const CHANGE_CURRENT_STREAM = "CHANGE_CURRENT_STREAM";
export const SEARCH_STREAM = "SEARCH_STREAM";
export const DEFAULT_CURRENT_STREAM = "DEFAULT_CURRENT_STREAM";
export const OPEN_CREATE_STREAM = "OPEN_CREATE_STREAM";
