export const SEARCH_GLOBAL = "SEARCH_GLOBAL";
export const FILTER_BY_SEARCH = "FILTER_BY_SEARCH";

export const RESULT_FILTER_BY_SEARCH_USERS = "RESULT_FILTER_BY_SEARCH_USERS";
export const RESULT_FILTER_BY_SEARCH_USERS_NULL =
  "RESULT_FILTER_BY_SEARCH_USERS_NULL";
export const RESULT_FILTER_BY_SEARCH_STREAMS =
  "RESULT_FILTER_BY_SEARCH_STREAMS";
export const RESULT_FILTER_BY_SEARCH_STREAMS_NULL =
  "RESULT_FILTER_BY_SEARCH_STREAMS_NULL";
export const RESULT_FILTER_BY_SEARCH_DOCUMENTS =
  "RESULT_FILTER_BY_SEARCH_DOCUMENTS";
export const RESULT_FILTER_BY_SEARCH_DOCUMENTS_NULL =
  "RESULT_FILTER_BY_SEARCH_DOCUMENTS_NULL";
