export const GET_TASKS = 'GET_TASKS';
export const CHANGE_CURRENT_MENU = 'CHANGE_CURRENT_MENU';
export const CREATE_TASK = 'CREATE_TASK';
export const CREATE_TASK_ALERT = 'CREATE_TASK_ALERT';
export const CREATE_TASK_LOADING = 'CREATE_TASK_LOADING';
export const GET_TASKS_GROUPS = 'GET_TASKS_GROUPS';
export const GET_TASK = 'GET_TASK';
export const TASK_NULL = 'TASK_NULL';
export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_TASK_ALERT = 'DELETE_TASK_ALERT';
export const OPEN_FILE_BY_ID = 'OPEN_FILE_BY_ID';
export const OPEN_FILE_BY_ID_NAME = 'OPEN_FILE_BY_ID_NAME';
export const FILE_DEFAULT_NULL = 'FILE_DEFAULT_NULL';
export const PATCH_TASK_ALERT = 'PATCH_TASK_ALERT';

export const CREATE_TASK_GROUP = 'CREATE_TASK_GROUP';
